### ISSUE TITLE
Repo should be renamed to bubbel-client-android

### ISSUE THREAD

**Issue by fuxibut** [MDeiml/blubbel-client-android#1]
Since we probably will be creating clients for other platforms.

**Comment by impfstoff** [comment]
if we use the ionic framework (supporting angular and react) we can export our application for android and ios.

**Comment by MDeiml** [comment]
(If anything should be renamed to b**l**ubbel-client-android)

**Comment by fuxibut** [comment]
Ah fuck you're right

**Comment by MDeiml** [comment]
Done
